yarnPath: .yarn/releases/yarn-4.5.1.cjs
packageExtensions:
  "@skyware/jetstream@*":
    dependencies:
      "@atcute/client": "^2.0.3"
  "typescript-eslint@^8":
    peerDependencies:
      typescript: "^5"
      eslint: ^9
  "@typescript-eslint/utils@^8":
    peerDependencies:
      typescript: ^5
  "@typescript-eslint/type-utils@^8":
    peerDependencies:
      typescript: ^5
      eslint: ^9
